project-meta:
  project-name: Bash Utility Scripts
  date-started: 2026-03-03
  last-updated: 2026-03-05
  languages:
    - Bash
  status: Experimental
  license: MIT
  version: 0.0.2

build:
  dev-environments:
    - Ubuntu (WSL2)
  target-platforms:
    - Linux
  interpreter:
    interpreter-name: Bash
    interpreter-version: 5.2.21

team:
  author: Ethan Kletschke
  contributors:
    - name: Ethan Kletschke
      role: Owner and Author
      github-username: ethanKletschke
